const fs = require('fs');
const path = require('path');

const prompts = {
  ikigai: [
    "What activity makes you lose track of time entirely?",
    "If money were not a factor, how would you spend your days?",
    "What is a small skill you have that brings joy to others?",
    "When did you last feel truly alive and engaged?",
    "What problem in the world do you feel drawn to solve?",
    "What did you love doing as a child that you've stopped doing?",
    "If you had to teach something to someone, what would it be?",
    "What values are you unwilling to compromise on?",
    "How can you align your daily work closer to your core values?",
    "What compliment do you receive most often from others?",
    "Describe a moment recently where you felt deep fulfillment.",
    "What is one thing you can do today that your future self will thank you for?",
    "Who inspires you, and what specific traits do you admire in them?",
    "What are you naturally good at that feels effortless to you?",
    "If you could master one new skill this year, what would it be?",
    "What topic could you talk about for hours without preparation?",
    "What does a 'perfect' day look like for you?",
    "What part of your current routine drains your energy the most?",
    "What part of your routine gives you the most energy?",
    "How do you want to be remembered by the people closest to you?",
    "What is a cause you care deeply about, and why?",
    "What do you constantly find yourself reading or learning about?",
    "When do you feel most authentically yourself?",
    "If you had to write a book, what would the subject be?",
    "What is a small way you made someone's life better today?",
    "What fear is currently holding you back from pursuing a passion?",
    "What does success mean to you, independent of society's definition?",
    "How can you bring more play and creativity into your life?",
    "What is a responsibility you enjoy having?",
    "If you had one extra hour every day, how would you use it?",
    "What is the most meaningful conversation you've had recently?",
    "What is something you believed deeply in the past that you no longer believe?",
    "How does your current career or path align with your true self?",
    "What is a talent you have that you rarely use?",
    "What environment or setting makes you feel most inspired?",
    "What is a recent challenge that made you realize your own strength?",
    "What is something you do that feels like a 'calling' rather than a 'chore'?",
    "If you could volunteer anywhere in the world, what would you do?",
    "What makes you feel deeply connected to humanity?",
    "What is a small daily habit that anchors your sense of purpose?",
    "What legacy do you hope to leave behind?",
    "What is a risk you took that ended up being incredibly rewarding?",
    "Who is someone you admire for their sense of purpose?",
    "What are three things you are uniquely equipped to contribute to the world?",
    "How do you define a 'life well-lived'?",
    "What is the most valuable lesson you've learned from a failure?",
    "What is a passion you've discovered recently?",
    "How do you stay true to yourself in difficult situations?",
    "What is a dream you've always had but never spoken out loud?",
    "What is one small step you can take today toward your life's purpose?"
  ],
  wabisabi: [
    "What is a physical 'flaw' in yourself that you can learn to find beautiful?",
    "Describe an old, worn object you own that holds deep sentimental value.",
    "What is a recent mistake you made that taught you a valuable lesson?",
    "How can you find peace in a situation that is currently unresolved?",
    "What is a part of your life that is messy but full of joy?",
    "Notice something aging around you (a leaf, a building, a person). What beauty is in its age?",
    "What is a completely ordinary moment from today that felt special?",
    "How can you embrace the unpredictability of your current circumstances?",
    "What is an imperfection in a loved one that makes them uniquely themselves?",
    "Write about a plan that fell apart, but led to something unexpected and good.",
    "What is a scar (physical or emotional) that you are grateful for?",
    "How does the changing of the seasons mirror your own life right now?",
    "Find a handmade object in your home. What does its irregularity tell you?",
    "What is something you need to let go of trying to make 'perfect'?",
    "How can you show yourself grace in a moment of weakness?",
    "What is a beautifully imperfect detail in nature you noticed today?",
    "Describe a memory that is bittersweet but beautiful.",
    "What is a project or hobby you can enjoy without needing to be 'good' at it?",
    "How does the passage of time add value to your life?",
    "What is something broken that you have repaired or repurposed?",
    "How can you find contentment in what you already have?",
    "What is an awkward or clumsy moment that makes you smile?",
    "How do you define beauty outside of societal standards?",
    "What is a relationship that is imperfect but deeply meaningful?",
    "Write about a time you found peace in silence or stillness.",
    "What is a 'flawed' trait in yourself that actually serves you well?",
    "How can you simplify a complicated area of your life?",
    "What is a natural process (like rust or decay) that you find fascinating?",
    "How do you handle the impermanence of the things you love?",
    "What is a rustic or unrefined texture you enjoy touching?",
    "Describe a meal that was simple and imperfect, but delicious.",
    "What is a piece of art that moves you despite (or because of) its flaws?",
    "How can you practice accepting things as they are today?",
    "What is a deeply human mistake you forgive yourself for?",
    "How does embracing impermanence change your daily priorities?",
    "What is a quiet, unnoticed corner of your home that you appreciate?",
    "Describe a time when doing 'less' resulted in a better outcome.",
    "What is a habit you have that is a little weird, but totally you?",
    "How can you find beauty in a gloomy or rainy day?",
    "What is a physical sign of aging in yourself that you can celebrate?",
    "How does accepting imperfection reduce your stress?",
    "What is a completely natural, unpolished sound you enjoy hearing?",
    "Write about a time when letting go of control brought you peace.",
    "What is an unfinished project that you still love?",
    "How can you apply the concept of Wabi-sabi to your workspace?",
    "What is a simple pleasure you enjoyed today without any grand expectations?",
    "Describe a time you felt beautiful precisely because you were vulnerable.",
    "How do you honor the history of the objects in your life?",
    "What is one way you can be gentler with your own imperfections today?",
    "Find an object near you. What story do its scratches and marks tell?"
  ],
  ma: [
    "Where in your schedule today can you intentionally create a 5-minute pause?",
    "What is a conversation where you can practice listening in silence before responding?",
    "Look around your room. Where is there empty space, and how does it make you feel?",
    "What is a commitment you can say 'no' to, in order to create more breathing room?",
    "Write about a time when silence spoke louder than words.",
    "How do you currently feel when you have 'nothing to do'?",
    "What is a thought or worry you need to create mental distance from?",
    "How can you simplify your physical environment to create more 'Ma'?",
    "What happens when you pause for 10 seconds before reacting in anger?",
    "Describe a moment today when you simply observed your surroundings without judgment.",
    "What is a sound you hear right now, and what is the silence beneath it?",
    "How can you create more space between your work life and personal life?",
    "Write about the physical sensation of taking a slow, deep breath.",
    "What is a relationship in your life that benefits from giving each other space?",
    "How can you practice 'Ma' while eating your next meal?",
    "What is a digital distraction you can remove to create mental space?",
    "Describe a moment of stillness you experienced in nature.",
    "How does the blank space on a page affect the way you read or write?",
    "What is a pause you took today that helped you regain clarity?",
    "How can you cultivate a sense of spaciousness in a crowded place?",
    "What is an activity you do purely for the sake of doing nothing else?",
    "How do you balance the need for connection with the need for solitude?",
    "Write about a time when waiting for something turned out to be a gift.",
    "How does creating physical space in your home affect your mind?",
    "What is a question you can leave unanswered for a while?",
    "How can you practice 'Ma' in your physical movements (e.g., walking, stretching)?",
    "Describe the feeling of an empty room.",
    "What is a gap in your knowledge that you are comfortable leaving empty for now?",
    "How can you introduce a mindful pause before you speak?",
    "What is a task you can intentionally do 50% slower today?",
    "How does silence make you feel: anxious, peaceful, or something else?",
    "Write about the space between inhaling and exhaling.",
    "What is a boundary you need to set to protect your personal space?",
    "How can you find 'Ma' in a piece of music you love?",
    "What is a moment today where you felt unhurried?",
    "How do you transition between different parts of your day? Is there a pause?",
    "What is something you can declutter from your mind right now?",
    "Describe the quietest moment of your day so far.",
    "How can you appreciate the 'white space' in a work of art?",
    "What is a habit you want to stop, to create space for a new one?",
    "How does the concept of 'Ma' change your perspective on productivity?",
    "Write about a time when a deliberate pause saved you from making a mistake.",
    "What is a space in your life that feels cluttered, and how can you clear it?",
    "How can you be fully present in the gaps between your scheduled events?",
    "What is a question you can ask yourself to invite stillness?",
    "Describe a time when you found comfort in isolation.",
    "How can you use 'Ma' to improve your focus?",
    "What is a silent communication you shared with someone recently?",
    "How does the night sky make you feel about the concept of vast space?",
    "What is one way you can embrace the 'empty' moments today instead of filling them with your phone?"
  ],
  kaizen: [
    "What is a 1-minute habit you can start today to improve your health?",
    "What is a small friction point in your morning routine, and how can you fix it?",
    "What is a tiny improvement you made this week that you are proud of?",
    "Identify a large goal. What is the smallest possible first step you can take?",
    "What is a skill you want to improve, and how can you practice it for 5 minutes today?",
    "How can you make your workspace 1% more efficient or pleasant?",
    "What is a repetitive task you do that you could streamline or automate?",
    "Write about a time when small, consistent efforts led to a massive result in your life.",
    "What is a bad habit you want to break, and what is one small obstacle you can put in its way?",
    "How can you improve the quality of your sleep by 1% tonight?",
    "What is a micro-habit you can attach to an existing routine (e.g., stretching while coffee brews)?",
    "What is a recent failure, and what small lesson can you extract from it?",
    "How can you improve your posture or physical alignment today?",
    "What is a small way you can better organize your digital life (e.g., deleting 5 emails)?",
    "Identify a process in your life that feels clumsy. How can you refine it?",
    "What is a tiny gesture you can do today to improve a relationship?",
    "How can you make your diet 1% healthier today?",
    "What is a small financial adjustment you can make to save or invest more?",
    "Write about a plateau you hit in the past and the small change that helped you break through.",
    "What is a task you've been procrastinating? Break it down into a 2-minute step.",
    "How can you improve your focus for just the next 15 minutes?",
    "What is a small piece of knowledge you acquired today?",
    "How can you make your end-of-day routine slightly more relaxing?",
    "What is a tiny tweak you can make to your exercise routine for better results?",
    "How can you improve the way you communicate with a specific colleague or friend?",
    "What is a small thing you can prepare tonight to make tomorrow morning smoother?",
    "Identify a recurrent annoyance in your home. Fix it right now. How does it feel?",
    "How can you upgrade the quality of the water or food you consume today?",
    "What is a small boundary you can set to protect your time?",
    "Write about a time when you gave up because a step was too big. What would a smaller step have been?",
    "How can you make your learning process 1% more effective?",
    "What is a tiny way you can practice gratitude today?",
    "How can you improve the lighting or air quality in your environment?",
    "What is a small act of kindness you can perform for a stranger?",
    "How can you reduce your screen time by just 5 minutes today?",
    "What is a micro-skill (e.g., typing speed, knife skills) you can practice today?",
    "How can you improve your emotional regulation in a small way?",
    "What is a small step you can take to become more environmentally friendly?",
    "Write about a complex problem you face. What is one tiny variable you can control?",
    "How can you upgrade a tool or instrument you use daily?",
    "What is a small way you can challenge your brain today (e.g., brush teeth with non-dominant hand)?",
    "How can you make your daily commute slightly more enjoyable or productive?",
    "What is a tiny way you can declutter your physical space right now?",
    "How can you improve your listening skills in your next conversation?",
    "What is a small step you can take toward a long-term financial goal?",
    "How can you make your creative process 1% more inspiring?",
    "What is a tiny commitment you can make and keep to build self-trust?",
    "How can you improve the way you handle stress in the moment?",
    "What is a small victory you achieved today that you can celebrate?",
    "If you improved by 1% every day for a year, where would you be next year?"
  ],
  shinrin: [
    "What is a specific detail you noticed about a tree or plant today?",
    "Describe the smell of the air outside right now.",
    "How does the weather today affect your internal mood?",
    "What is a sound of nature you heard today (even in a city)?",
    "Write about a childhood memory involving nature that brings you peace.",
    "How do you feel physically after spending time outdoors compared to indoors?",
    "Notice the sky. Describe its exact color and the shape of any clouds.",
    "What is a small piece of nature you can bring into your home or workspace?",
    "Describe the texture of a leaf, bark, or stone you touched recently.",
    "How does watching water (a river, rain, or ocean) make you feel?",
    "What is an animal or insect you observed today, and what was it doing?",
    "Write about a time when nature made you feel small in a comforting way.",
    "How can you incorporate a 10-minute nature walk into your daily routine?",
    "What is your favorite season, and what specific sensory details do you love about it?",
    "Describe the feeling of the sun or wind on your skin today.",
    "How does disconnecting from technology while outside change your perception?",
    "What is a natural landscape that you feel a deep connection to?",
    "How does observing the slow growth of plants change your perspective on time?",
    "Write about a time you found an unexpected piece of nature in an urban environment.",
    "What is a plant or flower that grows near you that you want to learn the name of?",
    "How do the shadows cast by trees change throughout the day?",
    "Describe the transition between day and night as you observed it recently.",
    "What is a natural scent that instantly relaxes you?",
    "How can you practice grounding (walking barefoot on earth) this week?",
    "Write about the resilience of a plant growing in a difficult place.",
    "What is a lesson about adaptability you can learn from a river or stream?",
    "How does the cycle of the moon affect your energy, if at all?",
    "Describe the sound of rain or wind against your window.",
    "What is a specific place in nature where you feel completely safe?",
    "How can you eat your next meal with a greater awareness of its origin in nature?",
    "Write about a time you got caught in the rain or snow. How did you react?",
    "What is a natural phenomenon (like a rainbow or eclipse) that left you in awe?",
    "How does the color green affect your mental state?",
    "Describe the differences in the air quality between morning, noon, and night.",
    "What is a lesson about letting go that you can learn from autumn leaves?",
    "How can you align your daily rhythms more closely with the sun?",
    "Write about a hike or walk that challenged you physically but rewarded you mentally.",
    "What is a specific bird song you recognize, and how does it make you feel?",
    "How does sitting under a large, old tree shift your perspective?",
    "What is a way you can give back to the natural environment today?",
    "Describe the beauty of a natural landscape in harsh conditions (e.g., a winter storm).",
    "How does observing an ant or spider change your view of diligence?",
    "What is a natural texture that you find deeply soothing to touch?",
    "Write about the vastness of the ocean or the mountains.",
    "How can you bring more awareness of nature into your urban commute?",
    "What is a wild food or herb you would like to learn how to forage?",
    "Describe the feeling of stepping onto grass after being indoors all day.",
    "How does the concept of an ecosystem apply to your own community?",
    "What is a profound silence you experienced in a forest or open field?",
    "Take a deep breath of outside air. What complex layers of scent can you detect?"
  ],
  gaman: [
    "What is a current difficulty you are facing that you cannot change, but must endure?",
    "Write about a time you persisted through physical or mental pain and came out stronger.",
    "How can you reframe a current frustration as a test of your patience?",
    "What is a situation where complaining will not help, and silence is stronger?",
    "Describe a person you admire for their stoic endurance.",
    "How does accepting discomfort change the way you experience it?",
    "What is a small inconvenience today that you can endure with grace?",
    "Write about a time when giving up was tempting, but holding on paid off.",
    "How can you practice emotional restraint when you feel angry or provoked?",
    "What is a long-term goal that requires significant daily endurance?",
    "How do you distinguish between enduring a necessary hardship and staying in a toxic situation?",
    "Describe a physical sensation of discomfort (e.g., cold, hunger) and practice observing it without reacting.",
    "What is a burden you carry that makes you a stronger person?",
    "How can you support someone else who is currently practicing Gaman?",
    "Write about a time when your patience was rewarded with a deeper understanding.",
    "How does the concept of Gaman differ from simply suppressing your emotions?",
    "What is a repetitive, tedious task that you can approach with a calm, enduring mind?",
    "How can you maintain your dignity in a humiliating or unfair situation?",
    "Describe a historical figure who exemplifies the spirit of Gaman.",
    "What is a difficult truth you need to accept and endure right now?",
    "How does focusing on the impermanence of pain help you endure it?",
    "Write about a time you had to be the 'rock' for your family or friends.",
    "How can you practice Gaman during a difficult conversation?",
    "What is a physical challenge (like a workout) where you can intentionally practice endurance?",
    "How does enduring hardship cultivate deep empathy for others?",
    "What is a delay or wait you are currently experiencing, and how can you wait peacefully?",
    "Describe a time when you chose the harder, more honorable path over the easy way out.",
    "How can you find quiet pride in your ability to withstand adversity?",
    "What is a sacrifice you are making now for a better future?",
    "Write about the silent strength of someone who never complains.",
    "How can you use deep breathing to endure a moment of acute stress?",
    "What is a situation where your endurance is an act of love?",
    "How does Gaman relate to your sense of personal honor or integrity?",
    "Describe a moment of exhaustion where you found a hidden reserve of energy.",
    "What is a way you can practice holding your tongue when criticized?",
    "How can you accept a loss or failure with quiet dignity?",
    "Write about a time when endurance was the only option you had.",
    "How does the ability to endure discomfort give you more freedom in life?",
    "What is a chronic issue you face, and how can you make peace with its presence?",
    "How can you channel your frustration into quiet, persistent action?",
    "Describe a time when you felt completely overwhelmed but kept moving forward anyway.",
    "What is a lesson about resilience you want to pass on to others?",
    "How does Gaman help you appreciate the easy, joyful moments of life more deeply?",
    "Write about a time you withstood peer pressure or societal expectations.",
    "How can you practice radical acceptance of your current reality?",
    "What is a physical scar or injury that reminds you of your endurance?",
    "How does the practice of Gaman prevent you from acting impulsively?",
    "Describe a situation where showing no reaction was the most powerful response.",
    "What is a difficult emotion (like grief or jealousy) that you must sit with and endure?",
    "How will enduring your current struggle make you uniquely equipped to help others later?"
  ],
  mononoaware: [
    "What is something beautiful in your life right now that you know won't last forever?",
    "Write about the feeling of finishing a great book or movie.",
    "How does knowing a moment is fleeting make it more valuable to you?",
    "Describe a memory from childhood that evokes a sweet, gentle sadness.",
    "What is a relationship that has ended, but you remain deeply grateful for?",
    "Notice a flower or plant that is blooming. Reflect on its brief lifespan.",
    "Write about a place you loved that no longer exists or has completely changed.",
    "How do you feel when the seasons change, particularly at the end of summer or autumn?",
    "What is a phase of your life that you miss, but are glad you moved on from?",
    "Describe the feeling of watching the sun set.",
    "How can you appreciate a fragile object more deeply because of its fragility?",
    "Write about a time you realized you were experiencing a 'last time' (e.g., last day of school).",
    "What is an old photograph that brings up a profound sense of nostalgia?",
    "How does the concept of impermanence help you forgive others?",
    "Describe a fleeting moment of connection with a stranger.",
    "What is a sound (like a train whistle or wind chime) that evokes a sense of melancholy?",
    "How do you honor the memory of someone who is no longer in your life?",
    "Write about the beauty of an aging face or hands.",
    "How can you be more fully present in conversations, knowing they are temporary?",
    "What is a piece of music that perfectly captures the feeling of Mono no aware?",
    "Describe the sensation of waking up from a beautiful, fleeting dream.",
    "How does the awareness of death enhance your appreciation for life?",
    "Write about a beloved item of clothing that is slowly wearing out.",
    "What is a tradition or ritual you participate in that connects you to the passage of time?",
    "How do you feel when you visit an old, historical ruin or building?",
    "Describe the feeling of holding a baby and knowing they will grow up quickly.",
    "What is a passing emotion you experienced today that you simply let wash over you?",
    "How can you find peace in the fact that your current worries are also impermanent?",
    "Write about the quiet sadness of a party or gathering coming to an end.",
    "What is a natural phenomenon (like cherry blossoms or snow) that is beautiful because it doesn't last?",
    "How does Mono no aware change your perspective on material possessions?",
    "Describe a time you watched someone you love sleeping.",
    "What is a phrase or saying from an older generation that resonates with you?",
    "How do you handle the bittersweet feeling of a child reaching a new milestone?",
    "Write about the scent of rain on dry earth, and how quickly it fades.",
    "What is a beautiful, temporary piece of art (like a sand mandala or ice sculpture) you admire?",
    "How can you practice letting go of a grudge by remembering the brevity of life?",
    "Describe the feeling of revisiting your hometown after a long time away.",
    "What is a fleeting thought or idea you had today that you want to capture?",
    "How does the vastness of the universe make your daily problems feel?",
    "Write about a time you felt a deep empathy for the vulnerability of another person.",
    "What is a seasonal food you love, and how does its limited availability make it special?",
    "How do you find comfort in the cyclical nature of the world?",
    "Describe the feeling of clearing out old belongings.",
    "What is a poignant lesson you learned from a pet?",
    "How can you embrace the sadness of saying goodbye at an airport or train station?",
    "Write about a time you witnessed a moment of pure, innocent joy.",
    "What is a scar on the landscape (like an old road or dried riverbed) that tells a story?",
    "How does Mono no aware help you combat the desire to control everything?",
    "Reflect on the exact moment you are in right now. It will never happen again. How does that feel?"
  ],
  hansei: [
    "What is a mistake you made today, and what did you learn from it?",
    "How did your actions today align (or misalign) with your core values?",
    "Who did you help today, and who could you have helped but didn't?",
    "What is a defensive reaction you had recently, and what insecurity was driving it?",
    "How did you spend your time today? Was it intentional or reactive?",
    "What is a harsh truth about yourself that you are avoiding?",
    "In what situation today did you let your ego dictate your behavior?",
    "What is a small promise you made to yourself recently that you broke?",
    "How well did you listen to others today? Did you interrupt or genuinely hear them?",
    "What is an area of your life where you are blaming others instead of taking responsibility?",
    "Describe a moment today when you felt jealous. What does that reveal about your own desires?",
    "How can you improve your behavior in a specific recurring conflict?",
    "What is a habit that is secretly draining your energy, and why do you keep doing it?",
    "Did you act with kindness today, even when it was difficult?",
    "What is an assumption you made about someone today that might be wrong?",
    "How did you handle stress or frustration today? Could you have handled it better?",
    "What is a fear that controlled one of your decisions this week?",
    "In what way were you dishonest (even slightly) today, and why?",
    "How are you currently procrastinating on something important?",
    "What is a privilege you have that you took for granted today?",
    "Describe a time recently when you spoke without thinking. What was the impact?",
    "How are you neglecting your physical or mental health right now?",
    "What is a relationship in your life that requires an apology from you?",
    "Did you consume more than you created today? (Content, resources, energy)",
    "What is a bias or prejudice you noticed in your own thinking recently?",
    "How can you be more patient with the people closest to you?",
    "What is a goal you've abandoned, and what was the real reason you stopped?",
    "In what area of your life are you seeking external validation instead of internal peace?",
    "How did you treat the people who serve you (waiters, drivers, colleagues) today?",
    "What is a deeply held belief you have that might be holding you back?",
    "How often did you complain today? What could you have done to fix the issue instead?",
    "What is a boundary you failed to enforce recently, and why?",
    "Describe a situation where you played the 'victim'. What was your actual role in it?",
    "How are you currently avoiding discomfort in a way that stunts your growth?",
    "What is a financial decision you made recently that was driven by emotion?",
    "Did you give your full attention to the tasks you did today, or were you distracted?",
    "What is a skill or subject you are pretending to know more about than you actually do?",
    "How can you show more gratitude for the efforts of others?",
    "What is a toxic trait you inherited, and how are you working to break the cycle?",
    "In what way did you try to control a situation that was out of your hands?",
    "How did you respond to constructive criticism recently?",
    "What is a small act of selfishness you committed today?",
    "How are you currently compromising your integrity for convenience?",
    "Describe a time you judged someone harshly. How are you similar to them?",
    "What is a 'need' you have that is actually just a 'want'?",
    "How can you be a better friend, partner, or family member tomorrow?",
    "What is a piece of advice you often give but rarely follow yourself?",
    "In what way are you letting your past define your future?",
    "How did you contribute to the overall atmosphere (positive or negative) of a room today?",
    "If today was a test of your character, what grade would you give yourself, and why?"
  ]
};

const fileContent = '\n\nexport const practicePrompts = ' + JSON.stringify(prompts, null, 2) + ';\n';
fs.appendFileSync(path.join(__dirname, '../src/data/prompts.js'), fileContent);
console.log('Prompts appended successfully.');
